name: Lint and Test

on:
  push:
  pull_request:
  # to trigger manually with webhook
  # curl -X POST https://api.github.com/repos/:owner/:repo/dispatches \
  # -H 'Accept: application/vnd.github.everest-preview+json' \
  # -H 'Authorization: token TOKEN_VALUE_HERE' \
  # --data '{"event_type":"lint-test","client_payload":{}}'
  repository_dispatch:
    types: [lint-test]

jobs:

  lint:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: lint
      run: |
        docker-compose run --rm dev
      env:
        RUN_TEST: no

  test:
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        python: ["2.7", "3.5", "3.6", "3.7", "3.8", "3.9"]
        flask: ["0.12.5", "1.0", "1.0.1", "1.0.2", "1.0.3", "1.0.4", "1.1.0", "1.1.1",
          "1.1.2", "1.1.3", "1.1.4", "2.0.0", "2.0.1", "2.0.2"]
        experimental: [false]
        include:
          - python: "3.10"
            # known issue: https://github.com/nose-devs/nose/issues/1099
            experimental: true
        exclude:
          # excludes flask versions from unsupported python versions
          - python: "2.7"
            flask: "1.1.3"
          - python: "2.7"
            flask: "2.0.0"
          - python: "2.7"
            flask: "2.0.1"
          - python: "2.7"
            flask: "2.0.2"
          - python: "3.5"
            flask: "1.1.3"
          - python: "3.5"
            flask: "2.0.0"
          - python: "3.5"
            flask: "2.0.1"
          - python: "3.5"
            flask: "2.0.2"
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: test
      run: |
        docker-compose run --rm dev
      env:
        CHECK_STYLE: no
        DEV_IMAGE: python:${{ matrix.python }}
        FLASK: ${{ matrix.flask }}
